FROM alpine AS builder
WORKDIR /usr/src/app
RUN apk add --no-cache --update nodejs yarn
COPY ./server/package.json ./server/yarn.lock ./
RUN yarn install --production=false

RUN apk --no-cache add \
    g++ make python git

#

FROM alpine
WORKDIR /usr/src/app
RUN apk add --no-cache --update nodejs yarn
COPY --from=builder /usr/src/app/node_modules ./node_modules
RUN yarn global add nodemon
RUN echo $NODE_ENV
#COPY ./server .
EXPOSE 8080
CMD [ "yarn", "dev" ]
