### register
POST http://localhost:81/api/v1/auth/register
Content-Type: application/json

{
  "name": "user01",
  "email": "user01@gmail.com",
  "password": "123@123a"
}

### login
POST http://localhost:81/api/v1/auth/login
Content-Type: application/json

{
  "email": "user01@gmail.com",
  "password": "123@123a"
}

### get user
GET http://localhost:81/api/v1/auth/user/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWI1MDNiNTI4NTA2YzE1NGIxNjY2NjciLCJuYW1lIjoidXNlcjAxIiwiZW1haWwiOiJ1c2VyMDFAZ21haWwuY29tIiwiaWF0IjoxNTg4OTMzNTk0LCJleHAiOjE1ODkwMTk5OTR9.ifMuQxao1ZXIPJ3RlPKDwNAqKOwWU_7qmKXbk26o_vw 

### upload avatar
PUT http://localhost:81/api/v1/auth/user/upload-avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWI1MDNiNTI4NTA2YzE1NGIxNjY2NjciLCJuYW1lIjoidXNlcjAxIiwiZW1haWwiOiJ1c2VyMDFAZ21haWwuY29tIiwiaWF0IjoxNTg4OTIxMzQ3LCJleHAiOjE1ODkwMDc3NDd9.-YdirCsG2G5BAqolaRn83_ASgTHSCpkxfFFZp14wPJg
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

avatar
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="default.jpg"
Content-Type: image/jpeg

< ./default.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--